global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'waggle-api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysqld-exporter:9104']